# Generated by Django 5.2.5 on 2025-08-10 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOwnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='seller/owners/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('legal_business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('established_date', models.DateField()),
                ('business_type', models.CharField(max_length=100)),
                ('taxpayer_number', models.CharField(blank=True, max_length=100)),
                ('trade_register_number', models.CharField(blank=True, max_length=100)),
                ('nid_front', models.ImageField(upload_to='seller/nid/front/')),
                ('nid_back', models.ImageField(upload_to='seller/nid/back/')),
                ('business_owner_images', models.ImageField(blank=True, null=True, upload_to='seller/owners/')),
                ('home_localization_plan', models.FileField(blank=True, null=True, upload_to='seller/localization/home/')),
                ('business_localization_plan', models.FileField(blank=True, null=True, upload_to='seller/localization/business/')),
                ('taxpayer_doc', models.FileField(blank=True, null=True, upload_to='seller/taxpayer/')),
                ('trade_register_doc', models.FileField(blank=True, null=True, upload_to='seller/trade_register/')),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_application', to=settings.AUTH_USER_MODEL)),
                ('owner_images', models.ManyToManyField(blank=True, to='users.sellerownerimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
