# Generated by Django 5.2.5 on 2025-08-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sellerownerimage_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplication',
            name='business_owner_images',
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
