# Generated by Django 4.2.18 on 2025-08-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
